// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_-Zs4uyd5gS9O1osZ7yqMEFAqMp2g94',
    appId: '1:43204267420:android:20be7e56e1795f8e8dcc59',
    messagingSenderId: '43204267420',
    projectId: 'banipay-4e717',
    storageBucket: 'banipay-4e717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhf_F-pJKuOFYqwhH0Dr96EV_ycS048lk',
    appId: '1:43204267420:ios:d01702ab100f07298dcc59',
    messagingSenderId: '43204267420',
    projectId: 'banipay-4e717',
    storageBucket: 'banipay-4e717.appspot.com',
    androidClientId: '43204267420-ifvcjoq0rmpos1v0bttspivfrdehgkep.apps.googleusercontent.com',
    iosClientId: '43204267420-jubsu2cfl18hd7vd6h0o6voesvi9ji97.apps.googleusercontent.com',
    iosBundleId: 'com.banipay.com.banipayPos',
  );
}
